### ISSUE TITLE
Spire - Saving a Second Activity bug

### ISSUE THREAD

**Issue by MortimerGreenwald** [Akkadius/spire#61] opened 2022-08-03 13:09 UTC
This bug has bigger implications. A server will stop functioning correctly if the task isn't saved to the DB correctly. 

To reproduce:
a. Open Spire
b. Go to Tasks and Create a New task
c. Set your description and rewards.
d. Hit Save
e. Go to the Activities Tab
f. Create your first activity. You can hit save After.
g. Use the + to create another activity. Enter in your details and hit Save.
f. Now that the task has been saved look at the tasks list and select another task.
g. Toggle back to the task you just created. The 2nd activity you just created will revert itself to Kill 1 Orc task.
h. At this point We've noticed on Karana that the task is corrupted. The server (see screenshot)
![image](https://user-images.githubusercontent.com/110543605/182998756-05175fe5-f260-48b4-a3a1-1e8377f5bde4.png)
Begins to toggle between 28 and 32,, and you loose connection with the world server. Eventually Clients cease to be able to zone into new zones with a "failed to zone XXXX" message. 
I. ... To resolve the server from completely nuking itself, i opened spire again and deleted the newly created task.. After that the server held a 30/30 zone stable and once i rebooted the server we're back in biz.

-Thanks
-ish (mort)

=======Old info Below but might be useful=========
I think there is a bug in Tasks. Essentially making a 2nd activity entry.
Steps: I cloned a task 
Click the + Activities to add another Step 1, 
Change goal method to kill a few npcs (list) within the Tab I hit save. 
Task flashes that it is saved and updated. 
However, if you go to another task and go back to the one you just saved the newly added 2nd activity isn't saved. 

![1](https://user-images.githubusercontent.com/110543605/182615721-0fa2f653-097d-487b-a855-a639bff2e386.png)
![2](https://user-images.githubusercontent.com/110543605/182615733-8743b01d-5ee6-4c4e-a423-4f56bf571526.png)

**Comment by Manwe-fv** [comment] 2022-08-16 18:06
I believe I found the cause for this issue. When creating an additional task activity, `zone_version` for that activity is being set to NULL by spire. This somehow causes zones to not spin up on reboot of server. Changing `zone_version `for that particular task activity to `-1` and rebooting allows the zones to be spun up as usual.

**Comment by Akkadius** [comment] 2022-08-22 05:46
Resolved in 1.13.4

**Closed by Akkadius** 2022-08-22 05:46 UTC
